# Generated by Django 4.0.4 on 2022-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, verbose_name='zip_code')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('county', models.CharField(max_length=100, verbose_name='zip_code')),
                ('state', models.CharField(max_length=100, verbose_name='zip_code')),
                ('users_ammount', models.PositiveIntegerField(default=0, verbose_name='ammount of users in the location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'user_locations',
                'unique_together': {('zip_code', 'city', 'county', 'state')},
            },
        ),
    ]
